In [1]:
#Import the numpy package under the name np
import numpy as np

In [2]:
# Create a null vector of size 10 
def null_array(n):
    x=np.zeros(n)
    return x
print(null_array(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#Create a null vector of size 10 but the fifth value which is 1 
def null_array(n):
    x=np.zeros(n)
    x[4] = 1
    return x
print(null_array(10))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#Create a vector with values ranging from 10 to 49 
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#Create a 3x3 matrix with values ranging from 0 to 8
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.array([1,2,0,0,4,0])
nonzero_indices = np.nonzero(x)[0]
print(nonzero_indices)

[0 1 4]


In [19]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.array([1,2,0,0,4,0])
x1 =np.nonzero(x)
print(x1)

(array([0, 1, 4], dtype=int64),)


In [25]:
#Create a 3x3 identity matrix 
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
#Create a 3x3x3 array with random values
x = np.random.random((3,3,3))
print(x)

[[[0.13743513 0.35122683 0.23168073]
  [0.05309719 0.17582937 0.55708572]
  [0.00320172 0.42345539 0.16198017]]

 [[0.02808408 0.65052783 0.28215541]
  [0.46611942 0.80671451 0.85549862]
  [0.1772603  0.94774054 0.90800678]]

 [[0.84598495 0.18366014 0.14134205]
  [0.47238817 0.6431706  0.438659  ]
  [0.99438965 0.66076091 0.68751523]]]


In [27]:
#Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10,10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[[3.61852606e-01 7.29539860e-01 6.37549543e-01 1.37222541e-01
   5.90485173e-01 7.35566255e-01 8.18784853e-01 2.70913600e-01
   3.62246479e-01 1.19651065e-01]
  [5.29198331e-01 2.38821987e-01 5.59529330e-01 9.63366870e-01
   8.01137536e-03 6.59506582e-01 4.32037869e-01 2.24456511e-01
   6.70427899e-01 8.88889128e-01]
  [6.92072250e-01 9.94615351e-01 5.24323749e-01 8.97540898e-01
   4.79162634e-01 7.53138786e-01 3.83874182e-01 3.67184031e-01
   8.89500611e-01 3.00186511e-01]
  [7.53042115e-01 4.18906333e-01 1.34777782e-02 9.45542391e-01
   2.75833804e-01 5.88545663e-01 7.19085347e-01 7.02652920e-01
   4.88718246e-01 5.41850799e-01]
  [5.86647917e-02 5.91469565e-01 7.70693355e-01 1.11022947e-01
   8.56233771e-01 9.46300323e-01 9.06548539e-01 3.26877486e-01
   1.79572317e-01 6.95654856e-01]
  [4.67649228e-01 9.27965641e-01 7.08174885e-01 2.65063304e-02
   5.69613793e-01 7.11215293e-01 3.09833748e-01 7.93790127e-01
   2.19607152e-01 1.12547623e-01]
  [6.16555179e-01 1.1833

In [29]:
#Create a random vector of size 30 and find the mean value
x = np.random.random(30)
mean_value = np.mean(x)

print(x)
print("Mean value:", mean_value)

[0.44722339 0.73636784 0.47744506 0.6943488  0.43852462 0.8453515
 0.29240479 0.71177573 0.71561747 0.53990602 0.79820005 0.03864331
 0.85582695 0.86754408 0.89185999 0.27118554 0.61617534 0.97345825
 0.4450668  0.20708088 0.55493138 0.92095396 0.50239652 0.33697862
 0.65916357 0.14545271 0.29155392 0.54688549 0.91772054 0.79527737]
Mean value: 0.5845106828712737


In [30]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
x = np.diag([1, 2, 3, 4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [31]:
#Normalize a 5x5 random matrix
x = np.random.random((5,5))
print("Original Array:")
print(x)
print("After normalization:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

Original Array:
[[0.09754461 0.17426168 0.96909046 0.59724232 0.72499995]
 [0.80888457 0.08572201 0.6526729  0.39343415 0.55985607]
 [0.27906255 0.63005859 0.00130085 0.18546281 0.79836771]
 [0.47003627 0.74582228 0.87096461 0.33545755 0.37442526]
 [0.13675325 0.77446695 0.89138455 0.58238449 0.44044525]]
After normalization:
[[0.09754461 0.17426168 0.96909046 0.59724232 0.72499995]
 [0.80888457 0.08572201 0.6526729  0.39343415 0.55985607]
 [0.27906255 0.63005859 0.00130085 0.18546281 0.79836771]
 [0.47003627 0.74582228 0.87096461 0.33545755 0.37442526]
 [0.13675325 0.77446695 0.89138455 0.58238449 0.44044525]]
[[0.099447   0.17871739 1.         0.61577586 0.74778556]
 [0.83446207 0.0872309  0.67305129 0.40518445 0.5771453 ]
 [0.28700629 0.64968433 0.         0.19029132 0.82359518]
 [0.48433608 0.76930092 0.89860829 0.34527825 0.3855429 ]
 [0.13996059 0.79889895 0.91970785 0.60042352 0.45376019]]


In [32]:
#How to find common values between two arrays? 
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [34]:
#Create a random vector of size 10 and sort it
x = np.random.random(10)
sort = np.sort(x)
print("Random Vector:")
print(x)
print("Sort Vestor:")
print(sort)

Random Vector:
[0.03448039 0.14614206 0.04959873 0.02978264 0.11961332 0.46337625
 0.18093648 0.33673345 0.85103916 0.24284307]
Sort Vestor:
[0.02978264 0.03448039 0.04959873 0.11961332 0.14614206 0.18093648
 0.24284307 0.33673345 0.46337625 0.85103916]


In [35]:
#Create random vector of size 10 and replace the maximum value by 0
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.69669526 0.20579952 0.         0.35119481 0.40936432 0.52037139
 0.44623726 0.20674348 0.78355265 0.8817983 ]


In [41]:
# Subtract the mean of each row of a matrix 
x = np.array([[2, 3, 3],
            [4, 5, 6],
            [7, 8, 9]])
row_means = np.mean(x,axis=1,keepdims=True)
result = x - row_means

print("Original Matrix:")
print(x)

print("Row Means:")
print(row_means)

print("Result")
print(result)

Original Matrix:
[[2 3 3]
 [4 5 6]
 [7 8 9]]
Row Means:
[[2.66666667]
 [5.        ]
 [8.        ]]
Result
[[-0.66666667  0.33333333  0.33333333]
 [-1.          0.          1.        ]
 [-1.          0.          1.        ]]


In [43]:
#How to get the n largest values of an array 
x = np.arange(10000)
np.random.shuffle(x)
y = 5

print (x[np.argsort(x)[-y:]])
print (x[np.argpartition(-x,y)[:y]])


[93 94 95 96 97 98 99]
[98 95 97 96 99 94 93]


In [45]:
#Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
x = np.random.random((5, 10))
modified_matrix = np.where(x > 4, x ** 2, x)

print("Original Matrix:")
print(x)

print("Modified Matrix:")
print(modified_matrix)

Original Matrix:
[[0.27389918 0.02218995 0.46656968 0.50538212 0.33614979 0.30484561
  0.73586878 0.39639288 0.93844082 0.09365519]
 [0.35983571 0.2788148  0.45532805 0.70027502 0.61818483 0.11844165
  0.74957747 0.71828953 0.18399045 0.49333577]
 [0.20164174 0.89598913 0.26327728 0.54277046 0.6777604  0.40088723
  0.55176903 0.95789656 0.33539614 0.13752675]
 [0.11052005 0.3900662  0.98883188 0.99494048 0.81939418 0.16560088
  0.72370997 0.56287793 0.14580697 0.76667052]
 [0.64566724 0.23783062 0.67282797 0.80083071 0.09151507 0.49066265
  0.59629616 0.58602923 0.53216007 0.51559108]]
Modified Matrix:
[[0.27389918 0.02218995 0.46656968 0.50538212 0.33614979 0.30484561
  0.73586878 0.39639288 0.93844082 0.09365519]
 [0.35983571 0.2788148  0.45532805 0.70027502 0.61818483 0.11844165
  0.74957747 0.71828953 0.18399045 0.49333577]
 [0.20164174 0.89598913 0.26327728 0.54277046 0.6777604  0.40088723
  0.55176903 0.95789656 0.33539614 0.13752675]
 [0.11052005 0.3900662  0.98883188 0.99494048