In [1]:
#Import the numpy package under the name np
import numpy as np

In [2]:
# Create a null vector of size 10 
def null_array(n):
    x=np.zeros(n)
    return x
print(null_array(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#Create a null vector of size 10 but the fifth value which is 1 
def null_array(n):
    x=np.zeros(n)
    x[4] = 1
    return x
print(null_array(10))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#Create a vector with values ranging from 10 to 49 
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#Create a 3x3 matrix with values ranging from 0 to 8
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.array([1,2,0,0,4,0])
nonzero_indices = np.nonzero(x)[0]
print(nonzero_indices)

[0 1 4]


In [19]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
x = np.array([1,2,0,0,4,0])
x1 =np.nonzero(x)
print(x1)

(array([0, 1, 4], dtype=int64),)


In [25]:
#Create a 3x3 identity matrix 
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
#Create a 3x3x3 array with random values
x = np.random.random((3,3,3))
print(x)

[[[0.13743513 0.35122683 0.23168073]
  [0.05309719 0.17582937 0.55708572]
  [0.00320172 0.42345539 0.16198017]]

 [[0.02808408 0.65052783 0.28215541]
  [0.46611942 0.80671451 0.85549862]
  [0.1772603  0.94774054 0.90800678]]

 [[0.84598495 0.18366014 0.14134205]
  [0.47238817 0.6431706  0.438659  ]
  [0.99438965 0.66076091 0.68751523]]]


In [3]:
#Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10,10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

NameError: name 'np' is not defined

In [4]:
#Create a random vector of size 30 and find the mean value
x = np.random.random(30)
mean_value = np.mean(x)

print(x)
print("Mean value:", mean_value)

NameError: name 'np' is not defined

In [13]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
x = np.diag([1, 2, 3, 4],k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [14]:
#Normalize a 5x5 random matrix
x = np.random.random((5,5))
print("Original Array:")
print(x)
print("After normalization:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

Original Array:
[[0.47450764 0.69134055 0.60354846 0.7398962  0.31457377]
 [0.2402443  0.34606967 0.97456864 0.12070918 0.37579873]
 [0.81286357 0.28300977 0.58250695 0.7860859  0.81084228]
 [0.69707308 0.89430249 0.83913498 0.77989181 0.33169011]
 [0.35817913 0.59385652 0.3511043  0.99857647 0.43108979]]
After normalization:
[[0.47450764 0.69134055 0.60354846 0.7398962  0.31457377]
 [0.2402443  0.34606967 0.97456864 0.12070918 0.37579873]
 [0.81286357 0.28300977 0.58250695 0.7860859  0.81084228]
 [0.69707308 0.89430249 0.83913498 0.77989181 0.33169011]
 [0.35817913 0.59385652 0.3511043  0.99857647 0.43108979]]
[[0.40302043 0.65002009 0.55001397 0.705331   0.22083588]
 [0.13616536 0.25671362 0.97265209 0.         0.29057871]
 [0.78844991 0.18488055 0.52604508 0.75794682 0.78614741]
 [0.65655014 0.88121897 0.81837631 0.75089098 0.24033351]
 [0.2705078  0.53897365 0.26244868 1.         0.35356211]]


In [7]:
#How to find common values between two arrays? 
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [8]:
#Create a random vector of size 10 and sort it
x = np.random.random(10)
sort = np.sort(x)
print("Random Vector:")
print(x)
print("Sort Vestor:")
print(sort)

Random Vector:
[0.04524014 0.86365961 0.6745412  0.44337873 0.16456196 0.05979823
 0.87394117 0.22112475 0.34597212 0.8035032 ]
Sort Vestor:
[0.04524014 0.05979823 0.16456196 0.22112475 0.34597212 0.44337873
 0.6745412  0.8035032  0.86365961 0.87394117]


In [9]:
#Create random vector of size 10 and replace the maximum value by 0
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.17123594 0.50074994 0.57964543 0.50478901 0.38182468 0.50200623
 0.29745592 0.041453   0.08439518 0.        ]


In [10]:
# Subtract the mean of each row of a matrix 
x = np.array([[2, 3, 3],
            [4, 5, 6],
            [7, 8, 9]])
row_means = np.mean(x,axis=1,keepdims=True)
result = x - row_means

print("Original Matrix:")
print(x)

print("Row Means:")
print(row_means)

print("Result")
print(result)

Original Matrix:
[[2 3 3]
 [4 5 6]
 [7 8 9]]
Row Means:
[[2.66666667]
 [5.        ]
 [8.        ]]
Result
[[-0.66666667  0.33333333  0.33333333]
 [-1.          0.          1.        ]
 [-1.          0.          1.        ]]


In [11]:
#How to get the n largest values of an array 
x = np.arange(10000)
np.random.shuffle(x)
y = 5

print (x[np.argsort(x)[-y:]])
print (x[np.argpartition(-x,y)[:y]])


[9995 9996 9997 9998 9999]
[9995 9999 9998 9996 9997]


In [12]:
#Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
x = np.random.random((5, 10))
modified_matrix = np.where(x > 4, x ** 2, x)

print("Original Matrix:")
print(x)

print("Modified Matrix:")
print(modified_matrix)

Original Matrix:
[[0.85494229 0.52656134 0.65532067 0.63075705 0.12964374 0.58412512
  0.40885673 0.53281187 0.66231296 0.24532593]
 [0.45555943 0.63047305 0.75737757 0.51065386 0.20030976 0.87948017
  0.6362572  0.68544495 0.54436664 0.9350336 ]
 [0.268084   0.18109357 0.1092825  0.89721234 0.58878906 0.11886062
  0.71125198 0.54013388 0.05187752 0.52034907]
 [0.58971938 0.1869661  0.44754467 0.53446581 0.84350808 0.37423478
  0.57651641 0.73155449 0.22541888 0.74208919]
 [0.16553979 0.81680115 0.45845583 0.46390787 0.58478866 0.99405324
  0.13474505 0.93463563 0.30603978 0.84515893]]
Modified Matrix:
[[0.85494229 0.52656134 0.65532067 0.63075705 0.12964374 0.58412512
  0.40885673 0.53281187 0.66231296 0.24532593]
 [0.45555943 0.63047305 0.75737757 0.51065386 0.20030976 0.87948017
  0.6362572  0.68544495 0.54436664 0.9350336 ]
 [0.268084   0.18109357 0.1092825  0.89721234 0.58878906 0.11886062
  0.71125198 0.54013388 0.05187752 0.52034907]
 [0.58971938 0.1869661  0.44754467 0.53446581