### Round 3

apply K-fold cross validation on your models before and check the model score. Note: So far we have not balanced the data.

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings('ignore')

In [2]:
#Read that data into Python and call the dataframe churnData.
df = pd.read_csv("DATA_Customer-Churn.csv")
df

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0     Female              0     Yes         No       1           No   
1       Male              0      No         No      34          Yes   
2       Male              0      No         No       2          Yes   
3       Male              0      No         No      45           No   
4     Female              0      No         No       2          Yes   
...      ...            ...     ...        ...     ...          ...   
7038    Male              0     Yes        Yes      24          Yes   
7039  Female              0     Yes        Yes      72          Yes   
7040  Female              0     Yes        Yes      11           No   
7041    Male              1     Yes         No       4          Yes   
7042    Male              0      No         No      66          Yes   

     OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0                No          Yes               No          No          No   
1               Yes           No              Yes          No          No   
2               Yes          Yes               No          No          No   
3               Yes           No              Yes         Yes          No   
4                No           No               No          No          No   
...             ...          ...              ...         ...         ...   
7038            Yes           No              Yes         Yes         Yes   
7039             No          Yes              Yes          No         Yes   
7040            Yes           No               No          No          No   
7041             No           No               No          No          No   
7042            Yes           No              Yes         Yes         Yes   

     StreamingMovies        Contract  MonthlyCharges TotalCharges Churn  
0                 No  Month-to-month           29.85        29.85    No  
1                 No        One year           56.95       1889.5    No  
2                 No  Month-to-month           53.85       108.15   Yes  
3                 No        One year           42.30      1840.75    No  
4                 No  Month-to-month           70.70       151.65   Yes  
...              ...             ...             ...          ...   ...  
7038             Yes        One year           84.80       1990.5    No  
7039             Yes        One year          103.20       7362.9    No  
7040              No  Month-to-month           29.60       346.45    No  
7041              No  Month-to-month           74.40        306.6   Yes  
7042             Yes        Two year          105.65       6844.5    No  

[7043 rows x 16 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   OnlineSecurity    7043 non-null   object 
 7   OnlineBackup      7043 non-null   object 
 8   DeviceProtection  7043 non-null   object 
 9   TechSupport       7043 non-null   object 
 10  StreamingTV       7043 non-null   object 
 11  StreamingMovies   7043 non-null   object 
 12  Contract          7043 non-null   object 
 13  MonthlyCharges    7043 non-null   float64
 14  TotalCharges      7043 non-null   object 
 15  Churn             7043 non-null   object 
dtypes: float64(1), int64(2), object(13)
memory

In [4]:
null_values = df['TotalCharges'].isnull().sum()
if null_values > 0:
    print("There are null values in the 'totalcharges' column.")
else:
    print("There are no null values in the 'totalcharges' column.")

There are no null values in the 'totalcharges' column.


In [5]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], downcast = 'float', errors = 'coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   OnlineSecurity    7043 non-null   object 
 7   OnlineBackup      7043 non-null   object 
 8   DeviceProtection  7043 non-null   object 
 9   TechSupport       7043 non-null   object 
 10  StreamingTV       7043 non-null   object 
 11  StreamingMovies   7043 non-null   object 
 12  Contract          7043 non-null   object 
 13  MonthlyCharges    7043 non-null   float64
 14  TotalCharges      7032 non-null   float32
 15  Churn             7043 non-null   object 
dtypes: float32(1), float64(1), int64(2), objec

In [6]:
df.isnull().any()

gender              False
SeniorCitizen       False
Partner             False
Dependents          False
tenure              False
PhoneService        False
OnlineSecurity      False
OnlineBackup        False
DeviceProtection    False
TechSupport         False
StreamingTV         False
StreamingMovies     False
Contract            False
MonthlyCharges      False
TotalCharges         True
Churn               False
dtype: bool

In [7]:
mean_totalcharges = df['TotalCharges'].mean()
df['TotalCharges'] = df['TotalCharges'].fillna(mean_totalcharges)

In [8]:
#Use the following features: tenure, SeniorCitizen, MonthlyCharges and TotalCharges: 

selected_columns = ['tenure', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges','Churn']  # Replace with the actual column names you want to select
new_df = df[selected_columns]
new_df

tenure  SeniorCitizen  MonthlyCharges  TotalCharges Churn
0          1              0           29.85     29.850000    No
1         34              0           56.95   1889.500000    No
2          2              0           53.85    108.150002   Yes
3         45              0           42.30   1840.750000    No
4          2              0           70.70    151.649994   Yes
...      ...            ...             ...           ...   ...
7038      24              0           84.80   1990.500000    No
7039      72              0          103.20   7362.899902    No
7040      11              0           29.60    346.450012    No
7041       4              1           74.40    306.600006   Yes
7042      66              0          105.65   6844.500000    No

[7043 rows x 5 columns]

In [9]:
#Churn transform from categorical to numerical data

from sklearn.preprocessing import LabelEncoder

# Assuming you have a DataFrame called 'df' with a categorical column named 'categorical_column'

# Create an instance of the LabelEncoder
label_encoder = LabelEncoder()

# Encode the categorical column
new_df['Churn'] = label_encoder.fit_transform(new_df['Churn'])
new_df

tenure  SeniorCitizen  MonthlyCharges  TotalCharges  Churn
0          1              0           29.85     29.850000      0
1         34              0           56.95   1889.500000      0
2          2              0           53.85    108.150002      1
3         45              0           42.30   1840.750000      0
4          2              0           70.70    151.649994      1
...      ...            ...             ...           ...    ...
7038      24              0           84.80   1990.500000      0
7039      72              0          103.20   7362.899902      0
7040      11              0           29.60    346.450012      0
7041       4              1           74.40    306.600006      1
7042      66              0          105.65   6844.500000      0

[7043 rows x 5 columns]

In [10]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   tenure          7043 non-null   int64  
 1   SeniorCitizen   7043 non-null   int64  
 2   MonthlyCharges  7043 non-null   float64
 3   TotalCharges    7043 non-null   float32
 4   Churn           7043 non-null   int32  
dtypes: float32(1), float64(1), int32(1), int64(2)
memory usage: 220.2 KB


In [11]:
#Split the data into a training set and a test set.
X = new_df[['tenure', 'SeniorCitizen', 'MonthlyCharges', 'TotalCharges']]
y = new_df['Churn']


# Split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Balancing

In [12]:
y.value_counts()

0    5174
1    1869
Name: Churn, dtype: int64

In [13]:
X, y = smote.fit_resample(X_train, y_train)

NameError: name 'smote' is not defined

In [ ]:
y.value_counts()

from imblearn.over_sampling import RandomOverSampler

# Create an instance of RandomOverSampler
oversampler = RandomOverSampler(random_state=42)

# Perform random oversampling
X_balanced, y_balanced = oversampler.fit_resample(X, y)

y_balanced.value_counts()

In [14]:
from imblearn.over_sampling import SMOTE

# Create an instance of SMOTE
smote = SMOTE(random_state=42)

# Perform SMOTE oversampling
X_balanced, y_balanced = smote.fit_resample(X, y)

In [15]:
y_balanced.value_counts()

0    5174
1    5174
Name: Churn, dtype: int64

## Decision Trees Classification
for me: don´t need scler

In [16]:
TT_SPLIT = 0.2     # ratio train/test size
RAND_STATE = 42   # specifies a sampling for repeatable results

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state = 42)
model = DecisionTreeClassifier(max_depth =5)
model.fit(X_train, y_train)
print("The (mean) accuracy on the test set is %.2f" %(model.score(X_test, y_test)))
print("The (mean) accuracy on the train data is %.2f" %(model.score(X_train, y_train)))
print("X has %d rows and %d columns"  %(X.shape[0],X.shape[1]))
print("y has %d rows"  %(y.shape[0]))

The (mean) accuracy on the test set is 0.79
The (mean) accuracy on the train data is 0.80
X has 7043 rows and 4 columns
y has 7043 rows


In [18]:
scores=cross_val_score(model, X_train, y_train, cv=5)
print("Cross validation scores: ", scores)
print("Score stats: %0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

Cross validation scores:  [0.79946761 0.79325643 0.7755102  0.78438332 0.77975133]
Score stats: 0.79 accuracy with a standard deviation of 0.01


In [19]:
scores=cross_val_score(model, X_train, y_train, cv=5) # 5 cv foldings
scores

array([0.79946761, 0.79325643, 0.7755102 , 0.78615794, 0.77975133])

In [20]:
print("Five-fold cv results: \n %0.2f mean accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))

Five-fold cv results: 
 0.79 mean accuracy with a standard deviation of 0.01


In [21]:
y_test

185     1
2715    0
3825    0
1807    1
132     0
       ..
6366    0
315     0
2439    0
5002    0
1161    1
Name: Churn, Length: 1409, dtype: int32

In [22]:
y_pred = cross_val_predict(model, X_test, y_test, cv=5)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
y_pred = cross_val_predict(model, X_train, y_train, cv=5)
y_pred

array([0, 0, 1, ..., 0, 1, 0])

### Knn_with scaler

In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)

MinMaxScaler()

In [25]:
model1 = DecisionTreeClassifier(max_depth = 5)
model2 = LogisticRegression()
model3 = KNeighborsClassifier()

model_pipeline = [model1, model2, model3]
model_names = ['Classification Tree', 'Logistic Regression', 'KNN']
scores = {}
i=0
for model in model_pipeline:
    mean_score = np.mean(cross_val_score(model, X_train, y_train, cv=5))
    scores[model_names[i]] = mean_score
    i = i+1
print(scores)

{'Classification Tree': 0.7859413933153769, 'Logistic Regression': 0.7875383963145841, 'KNN': 0.7630448178962681}


In [26]:
print("Comparing the 3 regression scores we find \n")

pd.DataFrame([scores], index=["score"])

Comparing the 3 regression scores we find 



Classification Tree  Logistic Regression       KNN
score             0.785941             0.787538  0.763045